/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GRAFICOS;

import MODELOS.Asteroide;
import MODELOS.Jugador;
import java.awt.Color;

/**
 *
 * @author Administrador
 */
public class Inicio extends javax.swing.JFrame {
    Interfaz miInterfaz;
    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        initComponents();
        this.miInterfaz = new Interfaz();
        this.miInterfaz.setVisible(true);  
        this.miInterfaz.setSize(700,700);
        this.miInterfaz.setBackground(Color.MAGENTA);
        this.add(this.miInterfaz);
        Jugador yo = new Jugador(350, 350, 25, "src/IMAGENES/nave.jpg", 3);
        this.miInterfaz.setYo(yo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bttnStart = new javax.swing.JButton();
        bttnStop = new javax.swing.JButton();
        bttnRemake = new javax.swing.JButton();
        bttnResume = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bttnStart.setText("START");
        bttnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnStartActionPerformed(evt);
            }
        });

        bttnStop.setText("STOP");

        bttnRemake.setText("REMAKE");
        bttnRemake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnRemakeActionPerformed(evt);
            }
        });

        bttnResume.setText("RESUME");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(746, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bttnResume)
                    .addComponent(bttnStop, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttnRemake)
                    .addComponent(bttnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(bttnStart)
                .addGap(18, 18, 18)
                .addComponent(bttnRemake)
                .addGap(18, 18, 18)
                .addComponent(bttnStop)
                .addGap(18, 18, 18)
                .addComponent(bttnResume)
                .addContainerGap(139, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnStartActionPerformed
        // este boton inicia el juego
        this.miInterfaz.setJugando(true);
    }//GEN-LAST:event_bttnStartActionPerformed

    private void bttnRemakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnRemakeActionPerformed
        // TODO add your handling code here:
        this.miInterfaz.setJugando(false);
    }//GEN-LAST:event_bttnRemakeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnRemake;
    private javax.swing.JButton bttnResume;
    private javax.swing.JButton bttnStart;
    private javax.swing.JButton bttnStop;
    // End of variables declaration//GEN-END:variables

    
}
